# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef5eee8cc9c5b63ff36a481201642309e0667a2ab1a4e05691668c073ced25e7ceec08efd0e269a2303a7f70f838d4347de7941600156b988aa73a10d4e3e0db

test:
  secret_key_base: e344bbadbee281d9ae8656c8ab98e9d2e3e668d9720c448a504f4c3b8e8d18ef8503f0cf6d9f1bbfad982d88bc361aaf0f5072662612f68f47190bcb08ad2cc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
